# Generated by Django 5.1 on 2024-08-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=1200)),
                ('activity', models.CharField(default='idle', max_length=200)),
            ],
        ),
    ]
