# Generated by Django 5.1 on 2024-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0003_rename_userame_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.SmallIntegerField()),
                ('user1', models.CharField(max_length=200)),
                ('user2', models.CharField(max_length=200)),
                ('gameStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
