# Generated by Django 5.1 on 2024-08-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userame',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
