# Generated by Django 5.1 on 2024-08-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0002_userinfo_userame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userame',
            new_name='username',
        ),
    ]
