# Generated by Django 5.1 on 2024-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginscreen', '0004_gameinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='activity',
            field=models.CharField(default='logged out', max_length=200),
        ),
    ]
